//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegisterEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Subject = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Letter { get; set; }
        public string Teacher { get; set; }
        public int SchoolId { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Subject> Subject { get; set; }
    }
}
