//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegisterEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolRegisterContainerContainer : DbContext
    {
        public SchoolRegisterContainerContainer()
            : base("name=SchoolRegisterContainerContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
    }
}
