//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolRegisterEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Class = new HashSet<Class>();
            this.Grades = new HashSet<Grades>();
            this.Notification = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Class> Class { get; set; }
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
